---
name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true # Enabling until there's a better solution.

      - name: Install dependencies
        run: |
          set -x
          asdf plugin add shellcheck && asdf install shellcheck latest && asdf global shellcheck latest
          asdf plugin add shfmt && asdf install shfmt latest && asdf global shfmt latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true # Enabling until there's a better solution.

      - name: Run ShellCheck
        run: scripts/shellcheck.sh

      - name: Run shfmt
        run: scripts/shfmt.sh

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "sloth version"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true # Enabling until there's a better solution.